version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  reviewers:
  - mvdstruijk
  assignees:
  - mvdstruijk
  schedule:
    interval: weekly
    day: sunday
    time: "07:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 25
